
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Download, FileText, Upload, Eye, FileUp } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';

// Mock documents data
const documentsData = {
  personalDocuments: [
    { id: 1, name: 'Employment Contract.pdf', uploadedBy: 'HR Department', date: 'January 10, 2025', size: '1.2 MB' },
    { id: 2, name: 'NDA Agreement.pdf', uploadedBy: 'HR Department', date: 'January 10, 2025', size: '0.8 MB' },
    { id: 3, name: 'Offer Letter.pdf', uploadedBy: 'HR Department', date: 'January 5, 2025', size: '0.5 MB' },
  ],
  payrollDocuments: [
    { id: 1, name: 'March 2025 Payslip.pdf', uploadedBy: 'Payroll System', date: 'March 31, 2025', size: '0.3 MB' },
    { id: 2, name: 'February 2025 Payslip.pdf', uploadedBy: 'Payroll System', date: 'February 28, 2025', size: '0.3 MB' },
    { id: 3, name: 'January 2025 Payslip.pdf', uploadedBy: 'Payroll System', date: 'January 31, 2025', size: '0.3 MB' },
  ],
  companyDocuments: [
    { id: 1, name: 'Employee Handbook 2025.pdf', uploadedBy: 'HR Department', date: 'January 2, 2025', size: '4.5 MB' },
    { id: 2, name: 'IT Security Policy.pdf', uploadedBy: 'IT Department', date: 'February 15, 2025', size: '1.8 MB' },
    { id: 3, name: 'Benefits Guide 2025.pdf', uploadedBy: 'HR Department', date: 'January 5, 2025', size: '2.2 MB' },
  ]
};

const Documents: React.FC = () => {
  const { user } = useAuth();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight mb-2">Documents</h1>
        <p className="text-muted-foreground">
          View and manage your personal and company documents
        </p>
      </div>

      <Tabs defaultValue="personal">
        <TabsList>
          <TabsTrigger value="personal">Personal Documents</TabsTrigger>
          <TabsTrigger value="payroll">Payroll Documents</TabsTrigger>
          <TabsTrigger value="company">Company Documents</TabsTrigger>
          <TabsTrigger value="upload">Upload Documents</TabsTrigger>
        </TabsList>
        
        <TabsContent value="personal" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Personal Documents</CardTitle>
              <CardDescription>Your employment-related documents</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Uploaded By</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {documentsData.personalDocuments.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-blue-500" />
                        <span className="font-medium">{doc.name}</span>
                      </TableCell>
                      <TableCell>{doc.uploadedBy}</TableCell>
                      <TableCell>{doc.date}</TableCell>
                      <TableCell>{doc.size}</TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button variant="ghost" size="icon">
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            <Download className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="payroll" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Payroll Documents</CardTitle>
              <CardDescription>Your payslips and tax documents</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {documentsData.payrollDocuments.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-green-500" />
                        <span className="font-medium">{doc.name}</span>
                      </TableCell>
                      <TableCell>{doc.uploadedBy}</TableCell>
                      <TableCell>{doc.date}</TableCell>
                      <TableCell>{doc.size}</TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button variant="ghost" size="icon">
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            <Download className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="company" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Company Documents</CardTitle>
              <CardDescription>Company-wide policies and handbooks</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Uploaded By</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {documentsData.companyDocuments.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell className="flex items-center">
                        <FileText className="h-4 w-4 mr-2 text-purple-500" />
                        <span className="font-medium">{doc.name}</span>
                      </TableCell>
                      <TableCell>{doc.uploadedBy}</TableCell>
                      <TableCell>{doc.date}</TableCell>
                      <TableCell>{doc.size}</TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button variant="ghost" size="icon">
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            <Download className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="upload" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Upload Document</CardTitle>
              <CardDescription>Upload personal documents for HR review</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="border-2 border-dashed rounded-lg p-8 text-center">
                <div className="mx-auto flex flex-col items-center justify-center">
                  <FileUp className="h-12 w-12 text-gray-400 mb-3" />
                  <h3 className="font-medium mb-1">Drag and drop files here</h3>
                  <p className="text-sm text-muted-foreground mb-4">or click to browse files</p>
                  <Button>
                    <Upload className="h-4 w-4 mr-2" />
                    Upload Files
                  </Button>
                </div>
              </div>
              
              <div className="mt-6">
                <h3 className="text-sm font-medium mb-3">Upload Guidelines</h3>
                <ul className="text-sm text-muted-foreground space-y-2 list-disc pl-5">
                  <li>Maximum file size: 10MB</li>
                  <li>Accepted file types: PDF, JPG, PNG, DOCX</li>
                  <li>Please ensure documents are clear and legible</li>
                  <li>For certificates, include both sides if necessary</li>
                  <li>Documents uploaded will be reviewed by HR before being approved</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default Documents;
